// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGKW-5tNOvB_2X1SLAqHT-03kLZmC6qv8',
    appId: '1:360323335328:web:cab2583ff4cb35796775c5',
    messagingSenderId: '360323335328',
    projectId: 'roomie-v1',
    authDomain: 'roomie-v1.firebaseapp.com',
    storageBucket: 'roomie-v1.appspot.com',
    measurementId: 'G-8XC2L40FWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaPSm6RrfBZAb_JnlPJTKGM6jGvF2bnuc',
    appId: '1:360323335328:android:8cce781e1cc8b0c36775c5',
    messagingSenderId: '360323335328',
    projectId: 'roomie-v1',
    storageBucket: 'roomie-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1cSYKvY1OQQs2cIlw_I8_7gBSMCWS5Ag',
    appId: '1:360323335328:ios:58982e759ec8f9336775c5',
    messagingSenderId: '360323335328',
    projectId: 'roomie-v1',
    storageBucket: 'roomie-v1.appspot.com',
    iosClientId: '360323335328-rmp2fvru824q02iebpdj2timp5k5vihr.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1cSYKvY1OQQs2cIlw_I8_7gBSMCWS5Ag',
    appId: '1:360323335328:ios:58982e759ec8f9336775c5',
    messagingSenderId: '360323335328',
    projectId: 'roomie-v1',
    storageBucket: 'roomie-v1.appspot.com',
    iosClientId: '360323335328-rmp2fvru824q02iebpdj2timp5k5vihr.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomie',
  );
}
