// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeKAekf_ElJ1QCq5K1F8nYbRAUMjCHtH8',
    appId: '1:1010332450091:web:ba8e3d5ed2f63b3ead596e',
    messagingSenderId: '1010332450091',
    projectId: 'roomie-7d33e',
    authDomain: 'roomie-7d33e.firebaseapp.com',
    storageBucket: 'roomie-7d33e.appspot.com',
    measurementId: 'G-B8BDQ8P1FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxrEcVHC1-zaVtbPnLGHeLpEN4B6yLOBg',
    appId: '1:1010332450091:android:992d2ace654af1cdad596e',
    messagingSenderId: '1010332450091',
    projectId: 'roomie-7d33e',
    storageBucket: 'roomie-7d33e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5WCV6tYkmZED99JhU7qAXUWyEFPsMnbc',
    appId: '1:1010332450091:ios:ba695be25dec715ead596e',
    messagingSenderId: '1010332450091',
    projectId: 'roomie-7d33e',
    storageBucket: 'roomie-7d33e.appspot.com',
    iosClientId: '1010332450091-1jnm4mmokbhj45li9plle273l3m1p8oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5WCV6tYkmZED99JhU7qAXUWyEFPsMnbc',
    appId: '1:1010332450091:ios:ba695be25dec715ead596e',
    messagingSenderId: '1010332450091',
    projectId: 'roomie-7d33e',
    storageBucket: 'roomie-7d33e.appspot.com',
    iosClientId: '1010332450091-1jnm4mmokbhj45li9plle273l3m1p8oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomie',
  );
}
